name: Renfe Ticket Monitor

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    # Runs the script every 15 minutes.
    # Use "*/30 * * * *" for every 30 min, or "0 * * * *" for every hour.
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Renfe Scraper
        env:
          # Pass GitHub secrets as environment variables to the script
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          # The -u flag ensures that prints are shown in real-time (unbuffered)
          python -u renfe_scraper.py
